-- Automatic Calorie Lookup milestone — shared Hebrew food reference data,
-- used to auto-fill calories per 100g when a coach adds a new food.
--
-- Run this file manually, once, in the Supabase Dashboard -> SQL Editor,
-- after 001_trainees.sql, 002_progress_logs.sql, and 003_nutrition.sql.

-- Shared (not coach-scoped) reference catalog. Seeded once below with
-- common Hebrew foods; the app only ever reads from it — rows are looked
-- up by name and used to prefill the coach's own `foods` entry, which then
-- acts as the per-coach cache for anything already resolved once.
create table public.food_reference_catalog (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) > 0),
  calories_per_100g numeric(6, 1) not null check (calories_per_100g >= 0),
  created_at timestamptz not null default now()
);

create unique index food_reference_catalog_name_idx
  on public.food_reference_catalog (lower(name));

alter table public.food_reference_catalog enable row level security;

-- Shared reference data: any logged-in coach may read it, nobody writes to
-- it from the app (seed/maintain it directly via the SQL Editor).
create policy food_reference_catalog_select_authenticated on public.food_reference_catalog
  for select
  using (auth.uid() is not null);

insert into public.food_reference_catalog (name, calories_per_100g) values
  ('תפוח', 52),
  ('בננה', 89),
  ('תפוז', 47),
  ('ענבים', 69),
  ('אבטיח', 30),
  ('מלון', 34),
  ('אגס', 57),
  ('אפרסק', 39),
  ('שזיף', 46),
  ('תות שדה', 32),
  ('קיווי', 61),
  ('מנגו', 60),
  ('אננס', 50),
  ('רימון', 83),
  ('לימון', 29),
  ('אבוקדו', 160),
  ('דובדבן', 63),
  ('משמש', 48),
  ('תמר', 277),
  ('צימוקים', 299),
  ('משמש מיובש', 241),
  ('תאנים מיובשות', 249),
  ('קוקוס', 354),
  ('עגבניה', 18),
  ('מלפפון', 16),
  ('גזר', 41),
  ('בצל', 40),
  ('פלפל אדום', 31),
  ('חסה', 15),
  ('כרוב', 25),
  ('ברוקולי', 34),
  ('כרובית', 25),
  ('חציל', 25),
  ('קישוא', 17),
  ('תירס', 86),
  ('תפוח אדמה', 77),
  ('תפוח אדמה אפוי', 93),
  ('בטטה', 86),
  ('שום', 149),
  ('פטריות', 22),
  ('תרד', 23),
  ('סלרי', 16),
  ('אורז לבן מבושל', 130),
  ('אורז מלא מבושל', 123),
  ('אורז בסמטי מבושל', 121),
  ('פסטה מבושלת', 131),
  ('לחם לבן', 265),
  ('לחם מלא', 247),
  ('פיתה', 275),
  ('קוסקוס מבושל', 112),
  ('בורגול מבושל', 83),
  ('שיבולת שועל', 389),
  ('קינואה מבושלת', 120),
  ('קרקר', 430),
  ('בייגלה', 380),
  ('פריכיות אורז', 387),
  ('דגני בוקר', 380),
  ('קורנפלקס', 378),
  ('גרנולה', 471),
  ('דייסת סולת', 95),
  ('וופל', 291),
  ('פנקייק', 227),
  ('חזה עוף צלוי', 165),
  ('שוק עוף', 209),
  ('בשר בקר טחון', 250),
  ('סטייק בקר', 271),
  ('הודו טחון', 189),
  ('סלמון', 208),
  ('טונה בשימורים', 116),
  ('דג אמנון', 96),
  ('דג בקלה', 82),
  ('שרימפס', 99),
  ('ביצה קשה', 155),
  ('ביצה מטוגנת', 196),
  ('שניצל עוף', 250),
  ('שניצל', 250),
  ('קבב', 280),
  ('נקניקיה', 300),
  ('המבורגר', 250),
  ('קציצות בשר', 220),
  ('קרוקט', 250),
  ('חומוס מבושל', 164),
  ('עדשים מבושלות', 116),
  ('שעועית מבושלת', 127),
  ('אפונה מבושלת', 81),
  ('טופו', 76),
  ('חומוס (ממרח)', 166),
  ('חלב 3%', 61),
  ('חלב 1%', 42),
  ('יוגורט טבעי', 59),
  ('יוגורט 3%', 62),
  ('יוגורט יווני', 97),
  ('קוטג'' 5%', 106),
  ('גבינה לבנה 5%', 108),
  ('גבינה צהובה', 350),
  ('גבינת שמנת', 342),
  ('לבן', 62),
  ('חמאה', 717),
  ('שמן זית', 884),
  ('חמאת בוטנים', 588),
  ('שקדים', 579),
  ('אגוזי מלך', 654),
  ('בוטנים', 567),
  ('טחינה', 595),
  ('זיתים', 115),
  ('זרעי חמניה', 584),
  ('זרעי דלעת', 559),
  ('שוקולד חלב', 535),
  ('שוקולד מריר', 546),
  ('עוגיות', 480),
  ('גלידה', 207),
  ('חטיף במבה', 534),
  ('ביסלי', 450),
  ('צ''יפס', 536),
  ('פופקורן', 387),
  ('דבש', 304),
  ('סוכר', 387),
  ('מרשמלו', 318),
  ('חטיף אנרגיה', 400),
  ('פלאפל', 333),
  ('שווארמה', 250),
  ('מלאווח', 377),
  ('בורקס', 300),
  ('סביח', 180),
  ('מג''דרה', 170),
  ('קובה', 220),
  ('שקשוקה', 120),
  ('פיצה', 266),
  ('לזניה', 135),
  ('פשטידה', 220),
  ('סלט ירקות', 40),
  ('מרק ירקות', 35),
  ('מרק עוף', 40),
  ('קולה', 42),
  ('מיץ תפוזים', 45),
  ('בירה', 43),
  ('יין אדום', 85);
