-- Food Reference Catalog USDA-Verified Expansion milestone.
--
-- Run this file manually, once, in the Supabase Dashboard -> SQL Editor,
-- after 039_food_reference_catalog_metadata.sql.
--
-- NOTE ON SCOPE: an earlier, memory-based draft of this milestone (never
-- applied, never committed) targeted 1,000+ products. This file
-- deliberately supersedes it with a much smaller, but individually
-- USDA-verified, set instead -- accuracy over count, per explicit
-- instruction. The catalog sits at 493 total products (222 corrected
-- pre-existing rows via 039 + 271 new rows here) after this pass, not
-- 1,000+; reaching 1,000 fully verified remains future work (see the
-- audit report's "excluded"/"needs_review" sections for the ~484+33
-- candidates that did not clear the bar this round).
--
-- Every one of the 269 rows below was individually verified against
-- a live USDA FoodData Central API response in this session: source_id
-- is the real USDA fdcId, source_url is a live link to that exact
-- record, source_checked_at is the date it was checked. See the
-- accompanying audit report for the full matching methodology and the
-- list of candidate products that could NOT be verified and were excluded
-- rather than guessed.
--
-- Restaurant/chain menu items and each coach's own private foods stay
-- entirely out of this pass, per instruction -- this table is the shared
-- generic-food reference catalog only.

insert into public.food_reference_catalog
  (name, calories_per_100g, protein_per_100g, category, basis, source_name, source_id, source_url, source_checked_at)
values
  ('קרמבולה (תות עץ סיני)', 31, 1.04, 'fruit', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Starfruit, raw', '2709228', 'https://fdc.nal.usda.gov/food-details/2709228/nutrients', CURRENT_DATE),  -- Starfruit, raw
  ('פפאיה', 43, 0.47, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Papayas, raw', '169926', 'https://fdc.nal.usda.gov/food-details/169926/nutrients', CURRENT_DATE),  -- Papayas, raw
  ('גויאבה', 48, 0.3, 'fruit', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Guava nectar', '2709344', 'https://fdc.nal.usda.gov/food-details/2709344/nutrients', CURRENT_DATE),  -- Guava nectar
  ('פסיפלורה', 69, 0.16, 'fruit', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Passion fruit nectar', '2709348', 'https://fdc.nal.usda.gov/food-details/2709348/nutrients', CURRENT_DATE),  -- Passion fruit nectar
  ('חבוש', 57, 0.4, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Quinces, raw', '168163', 'https://fdc.nal.usda.gov/food-details/168163/nutrients', CURRENT_DATE),  -- Quinces, raw
  ('תאנה טרייה', 74, 0.75, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Figs, raw', '173021', 'https://fdc.nal.usda.gov/food-details/173021/nutrients', CURRENT_DATE),  -- Figs, raw
  ('ליים', 30, 0.7, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Limes, raw', '168155', 'https://fdc.nal.usda.gov/food-details/168155/nutrients', CURRENT_DATE),  -- Limes, raw
  ('מנדרינה', 53, 0.81, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Tangerines, (mandarin oranges), raw', '169105', 'https://fdc.nal.usda.gov/food-details/169105/nutrients', CURRENT_DATE),  -- Tangerines, (mandarin oranges), raw
  ('ג''קפרוט טרי', 95, 1.72, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Jackfruit, raw', '174687', 'https://fdc.nal.usda.gov/food-details/174687/nutrients', CURRENT_DATE),  -- Jackfruit, raw
  ('תפוח מיובש', 243, 0.93, 'fruit', 'dried', 'USDA FoodData Central (Survey (FNDDS)) -- Apple, dried', '2709196', 'https://fdc.nal.usda.gov/food-details/2709196/nutrients', CURRENT_DATE),  -- Apple, dried
  ('דובדבן מיובש', 333, 1.25, 'fruit', 'dried', 'USDA FoodData Central (Survey (FNDDS)) -- Cherries, dried', '2709199', 'https://fdc.nal.usda.gov/food-details/2709199/nutrients', CURRENT_DATE),  -- Cherries, dried
  ('אננס מיובש', 347, 1.22, 'fruit', 'dried', 'USDA FoodData Central (Survey (FNDDS)) -- Pineapple, dried', '2709210', 'https://fdc.nal.usda.gov/food-details/2709210/nutrients', CURRENT_DATE),  -- Pineapple, dried
  ('אפרסק מיובש', 239, 3.61, 'fruit', 'dried', 'USDA FoodData Central (Survey (FNDDS)) -- Peach, dried', '2709207', 'https://fdc.nal.usda.gov/food-details/2709207/nutrients', CURRENT_DATE),  -- Peach, dried
  ('אגס מיובש', 262, 1.87, 'fruit', 'dried', 'USDA FoodData Central (Survey (FNDDS)) -- Pear, dried', '2709208', 'https://fdc.nal.usda.gov/food-details/2709208/nutrients', CURRENT_DATE),  -- Pear, dried
  ('אוכמניות מיובשות', 317, 2.5, 'fruit', 'dried', 'USDA FoodData Central (Survey (FNDDS)) -- Blueberries, dried', '2709198', 'https://fdc.nal.usda.gov/food-details/2709198/nutrients', CURRENT_DATE),  -- Blueberries, dried
  ('שזיף מיובש (שזיפים מיובשים)', 257, 2.1, 'fruit', 'dried', 'USDA FoodData Central (SR Legacy) -- Prune puree', '167780', 'https://fdc.nal.usda.gov/food-details/167780/nutrients', CURRENT_DATE),  -- Prune puree
  ('אננס משומר בקופסה', 60, 0.51, 'fruit', 'canned_drained', 'USDA FoodData Central (SR Legacy) -- Pineapple, canned, juice pack, drained', '167767', 'https://fdc.nal.usda.gov/food-details/167767/nutrients', CURRENT_DATE),  -- Pineapple, canned, juice pack, drained
  ('קולורבי', 27, 1.7, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Kohlrabi, raw', '168424', 'https://fdc.nal.usda.gov/food-details/168424/nutrients', CURRENT_DATE),  -- Kohlrabi, raw
  ('חמציץ (סלק עלים)', 19, 1.8, 'vegetable', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Chard, raw', '2709574', 'https://fdc.nal.usda.gov/food-details/2709574/nutrients', CURRENT_DATE),  -- Chard, raw
  ('עולש (אנדיב)', 17, 1.25, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Endive, raw', '168412', 'https://fdc.nal.usda.gov/food-details/168412/nutrients', CURRENT_DATE),  -- Endive, raw
  ('ארוגולה (רוקט)', 25, 2.58, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Arugula, raw', '169387', 'https://fdc.nal.usda.gov/food-details/169387/nutrients', CURRENT_DATE),  -- Arugula, raw
  ('קייל (כרוב עלים)', 35, 2.92, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Kale, raw', '168421', 'https://fdc.nal.usda.gov/food-details/168421/nutrients', CURRENT_DATE),  -- Kale, raw
  ('אפונת גינה טרייה (לא מבושלת)', 81, 5.42, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Peas, green, raw', '170419', 'https://fdc.nal.usda.gov/food-details/170419/nutrients', CURRENT_DATE),  -- Peas, green, raw
  ('שעועית ירוקה מבושלת', 35, 1.89, 'vegetable', 'boiled', 'USDA FoodData Central (SR Legacy) -- Beans, snap, green, cooked, boiled, drained, with salt', '169321', 'https://fdc.nal.usda.gov/food-details/169321/nutrients', CURRENT_DATE),  -- Beans, snap, green, cooked, boiled, drained, with salt
  ('שומר (פנוכיו)', 26.8924, 0.921875, 'vegetable', 'raw', 'USDA FoodData Central (Foundation) -- Fennel, bulb, raw', '2747655', 'https://fdc.nal.usda.gov/food-details/2747655/nutrients', CURRENT_DATE),  -- Fennel, bulb, raw
  ('עגבניות מיובשות בשמש', 258, 14.11, 'vegetable', 'dried', 'USDA FoodData Central (SR Legacy) -- Tomatoes, sun-dried', '168567', 'https://fdc.nal.usda.gov/food-details/168567/nutrients', CURRENT_DATE),  -- Tomatoes, sun-dried
  ('עגבניות משומרות בקופסה (פילטו)', 40.845, 1.578125, 'vegetable', 'canned_drained', 'USDA FoodData Central (Foundation) -- Tomato, puree, canned', '2685582', 'https://fdc.nal.usda.gov/food-details/2685582/nutrients', CURRENT_DATE),  -- Tomato, puree, canned
  ('בצל סגול', 44, 0.94, 'vegetable', 'raw', 'USDA FoodData Central (Foundation) -- Onions, red, raw', '790577', 'https://fdc.nal.usda.gov/food-details/790577/nutrients', CURRENT_DATE),  -- Onions, red, raw
  ('חמוצים (מלפפון חמוץ)', 14, 0.48, 'vegetable', 'canned_drained', 'USDA FoodData Central (Survey (FNDDS)) -- Pickles, dill', '2710078', 'https://fdc.nal.usda.gov/food-details/2710078/nutrients', CURRENT_DATE),  -- Pickles, dill
  ('כרוב כבוש (סאורקראוט)', 40, 0.9, 'vegetable', 'canned_drained', 'USDA FoodData Central (Survey (FNDDS)) -- Sauerkraut', '2709982', 'https://fdc.nal.usda.gov/food-details/2709982/nutrients', CURRENT_DATE),  -- Sauerkraut
  ('שעועית ירוקה טרייה', 39.9998, 1.96875, 'vegetable', 'raw', 'USDA FoodData Central (Foundation) -- Beans, snap, green, raw', '2346400', 'https://fdc.nal.usda.gov/food-details/2346400/nutrients', CURRENT_DATE),  -- Beans, snap, green, raw
  ('פטריות שיטאקי', 34, 2.24, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Mushrooms, shiitake, raw', '169242', 'https://fdc.nal.usda.gov/food-details/169242/nutrients', CURRENT_DATE),  -- Mushrooms, shiitake, raw
  ('תרד מבושל', 23, 2.97, 'vegetable', 'boiled', 'USDA FoodData Central (SR Legacy) -- Spinach, cooked, boiled, drained, with salt', '170531', 'https://fdc.nal.usda.gov/food-details/170531/nutrients', CURRENT_DATE),  -- Spinach, cooked, boiled, drained, with salt
  ('גזר מבושל', 35, 0.76, 'vegetable', 'boiled', 'USDA FoodData Central (SR Legacy) -- Carrots, cooked, boiled, drained, with salt', '169339', 'https://fdc.nal.usda.gov/food-details/169339/nutrients', CURRENT_DATE),  -- Carrots, cooked, boiled, drained, with salt
  ('אספרגוס טרי', 20, 2.2, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Asparagus, raw', '168389', 'https://fdc.nal.usda.gov/food-details/168389/nutrients', CURRENT_DATE),  -- Asparagus, raw
  ('ארטישוק טרי', 73, 2, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Jerusalem-artichokes, raw', '169236', 'https://fdc.nal.usda.gov/food-details/169236/nutrients', CURRENT_DATE),  -- Jerusalem-artichokes, raw
  ('כרישה מבושלת', 31, 0.81, 'vegetable', 'boiled', 'USDA FoodData Central (SR Legacy) -- Leeks, (bulb and lower leaf-portion), cooked, boiled, drained, with salt', '168535', 'https://fdc.nal.usda.gov/food-details/168535/nutrients', CURRENT_DATE),  -- Leeks, (bulb and lower leaf-portion), cooked, boiled, drained, with salt
  ('זיתים ירוקים ממולאים', 130, 1.15, 'vegetable', 'canned_drained', 'USDA FoodData Central (Foundation) -- Olives, green, Manzanilla, stuffed with pimiento', '332791', 'https://fdc.nal.usda.gov/food-details/332791/nutrients', CURRENT_DATE),  -- Olives, green, Manzanilla, stuffed with pimiento
  ('צנון טרי', 16, 0.68, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Radishes, raw', '169276', 'https://fdc.nal.usda.gov/food-details/169276/nutrients', CURRENT_DATE),  -- Radishes, raw
  ('סלק טרי', 44.6205, 1.6875, 'vegetable', 'raw', 'USDA FoodData Central (Foundation) -- Beets, raw', '2685576', 'https://fdc.nal.usda.gov/food-details/2685576/nutrients', CURRENT_DATE),  -- Beets, raw
  ('חסה רומאית', 21, 0.98, 'vegetable', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Romaine lettuce, raw', '2709590', 'https://fdc.nal.usda.gov/food-details/2709590/nutrients', CURRENT_DATE),  -- Romaine lettuce, raw
  ('תרד קפוא מבושל', 59, 3.88, 'vegetable', 'boiled', 'USDA FoodData Central (Survey (FNDDS)) -- Spinach, frozen, cooked with oil', '2709624', 'https://fdc.nal.usda.gov/food-details/2709624/nutrients', CURRENT_DATE),  -- Spinach, frozen, cooked with oil
  ('אפונה קפואה מבושלת', 102, 4.99, 'vegetable', 'boiled', 'USDA FoodData Central (Survey (FNDDS)) -- Green peas, frozen, cooked with oil', '2709968', 'https://fdc.nal.usda.gov/food-details/2709968/nutrients', CURRENT_DATE),  -- Green peas, frozen, cooked with oil
  ('עגבנייה מיובשת בשמן', 213, 5.06, 'vegetable', 'dried', 'USDA FoodData Central (SR Legacy) -- Tomatoes, sun-dried, packed in oil, drained', '169384', 'https://fdc.nal.usda.gov/food-details/169384/nutrients', CURRENT_DATE),  -- Tomatoes, sun-dried, packed in oil, drained
  ('חסה אייסברג', 17.10875, 0.7425, 'vegetable', 'raw', 'USDA FoodData Central (Foundation) -- Lettuce, iceberg, raw', '2346388', 'https://fdc.nal.usda.gov/food-details/2346388/nutrients', CURRENT_DATE),  -- Lettuce, iceberg, raw
  ('תירס מתוק משומר', 67, 2.29, 'vegetable', 'canned_drained', 'USDA FoodData Central (SR Legacy) -- Corn, sweet, white, canned, whole kernel, drained solids', '169361', 'https://fdc.nal.usda.gov/food-details/169361/nutrients', CURRENT_DATE),  -- Corn, sweet, white, canned, whole kernel, drained solids
  ('פסטה גולמית (יבשה)', 371, 13.04, 'grain_carb', 'raw', 'USDA FoodData Central (SR Legacy) -- Pasta, dry, enriched', '169736', 'https://fdc.nal.usda.gov/food-details/169736/nutrients', CURRENT_DATE),  -- Pasta, dry, enriched
  ('אורז לבן גולמי', 358.705, 7.03885, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Rice, white, long grain, unenriched, raw', '2512381', 'https://fdc.nal.usda.gov/food-details/2512381/nutrients', CURRENT_DATE),  -- Rice, white, long grain, unenriched, raw
  ('אורז מלא גולמי', 365.518, 7.25305, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Rice, brown, long grain, unenriched, raw', '2512380', 'https://fdc.nal.usda.gov/food-details/2512380/nutrients', CURRENT_DATE),  -- Rice, brown, long grain, unenriched, raw
  ('פסטה מלאה גולמית (יבשה)', 352, 13.87, 'grain_carb', 'raw', 'USDA FoodData Central (SR Legacy) -- Pasta, whole-wheat, dry (Includes foods for USDA''s Food Distribution Program)', '169738', 'https://fdc.nal.usda.gov/food-details/169738/nutrients', CURRENT_DATE),  -- Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)
  ('בורגול גולמי', 372.341, 11.75625, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Bulgur, dry, raw', '2710820', 'https://fdc.nal.usda.gov/food-details/2710820/nutrients', CURRENT_DATE),  -- Bulgur, dry, raw
  ('אורז לתשתית עם ירקות (פילף)', 137, 3.29, 'grain_carb', 'cooked', 'USDA FoodData Central (Survey (FNDDS)) -- Rice pilaf', '2709077', 'https://fdc.nal.usda.gov/food-details/2709077/nutrients', CURRENT_DATE),  -- Rice pilaf
  ('כוסמת מבושלת', 92, 3.38, 'grain_carb', 'cooked', 'USDA FoodData Central (SR Legacy) -- Buckwheat groats, roasted, cooked', '170686', 'https://fdc.nal.usda.gov/food-details/170686/nutrients', CURRENT_DATE),  -- Buckwheat groats, roasted, cooked
  ('דוחן מבושל', 119, 3.51, 'grain_carb', 'cooked', 'USDA FoodData Central (SR Legacy) -- Millet, cooked', '168871', 'https://fdc.nal.usda.gov/food-details/168871/nutrients', CURRENT_DATE),  -- Millet, cooked
  ('קמח לבן (חיטה)', 366, 10.9, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Flour, wheat, all-purpose, enriched, bleached', '789890', 'https://fdc.nal.usda.gov/food-details/789890/nutrients', CURRENT_DATE),  -- Flour, wheat, all-purpose, enriched, bleached
  ('קמח מלא (חיטה)', 370, 15.1, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Flour, whole wheat, unenriched', '790085', 'https://fdc.nal.usda.gov/food-details/790085/nutrients', CURRENT_DATE),  -- Flour, whole wheat, unenriched
  ('קמח שיפון', 359.4, 8.3952, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Flour, rye', '2512375', 'https://fdc.nal.usda.gov/food-details/2512375/nutrients', CURRENT_DATE),  -- Flour, rye
  ('קמח אורז', 365.25, 7.19, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Flour, rice, brown', '1104812', 'https://fdc.nal.usda.gov/food-details/1104812/nutrients', CURRENT_DATE),  -- Flour, rice, brown
  ('אטריות סובה מבושלות', 99, 5.06, 'grain_carb', 'cooked', 'USDA FoodData Central (SR Legacy) -- Noodles, japanese, soba, cooked', '168907', 'https://fdc.nal.usda.gov/food-details/168907/nutrients', CURRENT_DATE),  -- Noodles, japanese, soba, cooked
  ('אטריות ביצים מבושלות', 138, 4.54, 'grain_carb', 'cooked', 'USDA FoodData Central (SR Legacy) -- Noodles, egg, enriched, cooked', '169732', 'https://fdc.nal.usda.gov/food-details/169732/nutrients', CURRENT_DATE),  -- Noodles, egg, enriched, cooked
  ('לחם קוואקר (חיטה נבטים)', 188, 13.16, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Bread, wheat, sprouted', '171850', 'https://fdc.nal.usda.gov/food-details/171850/nutrients', CURRENT_DATE),  -- Bread, wheat, sprouted
  ('לחם ללא גלוטן', 248, 4.31, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Bread, gluten free', '2707797', 'https://fdc.nal.usda.gov/food-details/2707797/nutrients', CURRENT_DATE),  -- Bread, gluten free
  ('לחם מחמצת (סוראדו)', 272, 10.75, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Bread, french or vienna (includes sourdough)', '172675', 'https://fdc.nal.usda.gov/food-details/172675/nutrients', CURRENT_DATE),  -- Bread, french or vienna (includes sourdough)
  ('לחם שום', 350, 8.36, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Garlic bread, frozen', '167939', 'https://fdc.nal.usda.gov/food-details/167939/nutrients', CURRENT_DATE),  -- Garlic bread, frozen
  ('קרואסון חמאה', 406, 8.2, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Croissants, butter', '174987', 'https://fdc.nal.usda.gov/food-details/174987/nutrients', CURRENT_DATE),  -- Croissants, butter
  ('דניש גבינה', 374, 8, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Danish pastry, cheese', '172754', 'https://fdc.nal.usda.gov/food-details/172754/nutrients', CURRENT_DATE),  -- Danish pastry, cheese
  ('עוגיות חמאה', 467, 6.1, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cookies, butter, commercially prepared, enriched', '174950', 'https://fdc.nal.usda.gov/food-details/174950/nutrients', CURRENT_DATE),  -- Cookies, butter, commercially prepared, enriched
  ('עוגיות שיבולת שועל', 441, 5.86, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cookies, oatmeal, with raisins', '174963', 'https://fdc.nal.usda.gov/food-details/174963/nutrients', CURRENT_DATE),  -- Cookies, oatmeal, with raisins
  ('ביסקוויט פשוט (טי-בורד)', 446, 6.9, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cookies, animal crackers (includes arrowroot, tea biscuits)', '168014', 'https://fdc.nal.usda.gov/food-details/168014/nutrients', CURRENT_DATE),  -- Cookies, animal crackers (includes arrowroot, tea biscuits)
  ('עוגת שיש (מרמור)', 347, 3.07, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Cake or cupcake, marble', '2707880', 'https://fdc.nal.usda.gov/food-details/2707880/nutrients', CURRENT_DATE),  -- Cake or cupcake, marble
  ('פאי דלעת', 249, 4.76, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Pie, pumpkin', '2708011', 'https://fdc.nal.usda.gov/food-details/2708011/nutrients', CURRENT_DATE),  -- Pie, pumpkin
  ('עוגת בננה', 368, 8.97, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cereals, QUAKER, Instant Oatmeal, Banana Bread, dry', '174638', 'https://fdc.nal.usda.gov/food-details/174638/nutrients', CURRENT_DATE),  -- Cereals, QUAKER, Instant Oatmeal, Banana Bread, dry
  ('קאפקייק שוקולד', 360, 3.7, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Cake or cupcake, German chocolate', '2707869', 'https://fdc.nal.usda.gov/food-details/2707869/nutrients', CURRENT_DATE),  -- Cake or cupcake, German chocolate
  ('חומוס יבש (גולמי)', 378, 20.47, 'legume', 'raw', 'USDA FoodData Central (SR Legacy) -- Chickpeas (garbanzo beans, bengal gram), mature seeds, raw', '173756', 'https://fdc.nal.usda.gov/food-details/173756/nutrients', CURRENT_DATE),  -- Chickpeas (garbanzo beans, bengal gram), mature seeds, raw
  ('עדשים אדומות יבשות (גולמיות)', 358, 23.91, 'legume', 'raw', 'USDA FoodData Central (SR Legacy) -- Lentils, pink or red, raw', '174284', 'https://fdc.nal.usda.gov/food-details/174284/nutrients', CURRENT_DATE),  -- Lentils, pink or red, raw
  ('שעועית לבנה יבשה (גולמית)', 333, 23.36, 'legume', 'raw', 'USDA FoodData Central (SR Legacy) -- Beans, white, mature seeds, raw', '175202', 'https://fdc.nal.usda.gov/food-details/175202/nutrients', CURRENT_DATE),  -- Beans, white, mature seeds, raw
  ('שעועית שחורה מבושלת', 132, 8.86, 'legume', 'cooked', 'USDA FoodData Central (SR Legacy) -- Beans, black, mature seeds, cooked, boiled, with salt', '175237', 'https://fdc.nal.usda.gov/food-details/175237/nutrients', CURRENT_DATE),  -- Beans, black, mature seeds, cooked, boiled, with salt
  ('שעועית אדומה מבושלת', 127, 8.67, 'legume', 'cooked', 'USDA FoodData Central (SR Legacy) -- Beans, kidney, red, mature seeds, cooked, boiled, with salt', '175242', 'https://fdc.nal.usda.gov/food-details/175242/nutrients', CURRENT_DATE),  -- Beans, kidney, red, mature seeds, cooked, boiled, with salt
  ('שעועית פינטו מבושלת', 143, 9.01, 'legume', 'cooked', 'USDA FoodData Central (SR Legacy) -- Beans, pinto, mature seeds, cooked, boiled, with salt', '173796', 'https://fdc.nal.usda.gov/food-details/173796/nutrients', CURRENT_DATE),  -- Beans, pinto, mature seeds, cooked, boiled, with salt
  ('אפונה שדה (חצי) מבושלת', 116, 8.34, 'legume', 'cooked', 'USDA FoodData Central (SR Legacy) -- Peas, split, mature seeds, cooked, boiled, with salt', '175257', 'https://fdc.nal.usda.gov/food-details/175257/nutrients', CURRENT_DATE),  -- Peas, split, mature seeds, cooked, boiled, with salt
  ('עדשים צהובות מבושלות', 114, 9.02, 'legume', 'cooked', 'USDA FoodData Central (SR Legacy) -- Lentils, mature seeds, cooked, boiled, with salt', '175254', 'https://fdc.nal.usda.gov/food-details/175254/nutrients', CURRENT_DATE),  -- Lentils, mature seeds, cooked, boiled, with salt
  ('טמפה', 192, 20.29, 'legume', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Tempeh', '174272', 'https://fdc.nal.usda.gov/food-details/174272/nutrients', CURRENT_DATE),  -- Tempeh
  ('שעועית ירוקה יבשה (מש) מבושלת', 156, 6.52, 'legume', 'cooked', 'USDA FoodData Central (Survey (FNDDS)) -- Mung beans, cooked', '2707389', 'https://fdc.nal.usda.gov/food-details/2707389/nutrients', CURRENT_DATE),  -- Mung beans, cooked
  ('חזה עוף עם עור גולמי', 126.905, 21.40625, 'meat_poultry', 'raw', 'USDA FoodData Central (Foundation) -- Chicken, breast, meat and skin, raw', '2727569', 'https://fdc.nal.usda.gov/food-details/2727569/nutrients', CURRENT_DATE),  -- Chicken, breast, meat and skin, raw
  ('חזה עוף גולמי (ללא עור)', 106.034, 22.525, 'meat_poultry', 'raw', 'USDA FoodData Central (Foundation) -- Chicken, breast, boneless, skinless, raw', '2646170', 'https://fdc.nal.usda.gov/food-details/2646170/nutrients', CURRENT_DATE),  -- Chicken, breast, boneless, skinless, raw
  ('שוק עוף גולמי', 144.07, 18.6125, 'meat_poultry', 'raw', 'USDA FoodData Central (Foundation) -- Chicken, thigh, boneless, skinless, raw', '2646171', 'https://fdc.nal.usda.gov/food-details/2646171/nutrients', CURRENT_DATE),  -- Chicken, thigh, boneless, skinless, raw
  ('כנפיים עוף מטוגנות', 289, 19.4, 'meat_poultry', 'fried', 'USDA FoodData Central (Survey (FNDDS)) -- Chicken wing, fried, coated, from raw', '2706065', 'https://fdc.nal.usda.gov/food-details/2706065/nutrients', CURRENT_DATE),  -- Chicken wing, fried, coated, from raw
  ('סטייק בקר גולמי (סינטה)', 140.144, 21.975, 'meat_poultry', 'raw', 'USDA FoodData Central (Foundation) -- Beef, top sirloin steak, raw', '2727574', 'https://fdc.nal.usda.gov/food-details/2727574/nutrients', CURRENT_DATE),  -- Beef, top sirloin steak, raw
  ('פילה בקר גולמי', 143.2, 21.09375, 'meat_poultry', 'raw', 'USDA FoodData Central (Foundation) -- Beef, tenderloin steak, raw', '2727573', 'https://fdc.nal.usda.gov/food-details/2727573/nutrients', CURRENT_DATE),  -- Beef, tenderloin steak, raw
  ('אנטריקוט גולמי', 254.11, 18.74375, 'meat_poultry', 'raw', 'USDA FoodData Central (Foundation) -- Beef, ribeye, steak, boneless, choice, raw', '2646172', 'https://fdc.nal.usda.gov/food-details/2646172/nutrients', CURRENT_DATE),  -- Beef, ribeye, steak, boneless, choice, raw
  ('צלעות בקר צלויות (ריבס)', 197, 27.23, 'meat_poultry', 'roasted', 'USDA FoodData Central (SR Legacy) -- Beef, New Zealand, imported, ribs prepared, cooked, fast roasted', '173089', 'https://fdc.nal.usda.gov/food-details/173089/nutrients', CURRENT_DATE),  -- Beef, New Zealand, imported, ribs prepared, cooked, fast roasted
  ('בשר צלי כתף (פושקה) מבושל', 216, 24.61, 'meat_poultry', 'cooked', 'USDA FoodData Central (SR Legacy) -- Beef, chuck, clod roast, separable lean and fat, trimmed to 0" fat, choice, cooked, roasted', '174023', 'https://fdc.nal.usda.gov/food-details/174023/nutrients', CURRENT_DATE),  -- Beef, chuck, clod roast, separable lean and fat, trimmed to 0" fat, choice, cooked, roasted
  ('קורנביף משומר', 250, 27.1, 'meat_poultry', 'canned_drained', 'USDA FoodData Central (SR Legacy) -- Beef, cured, corned beef, canned', '170602', 'https://fdc.nal.usda.gov/food-details/170602/nutrients', CURRENT_DATE),  -- Beef, cured, corned beef, canned
  ('כבד בקר גולמי', 135, 20.36, 'meat_poultry', 'raw', 'USDA FoodData Central (SR Legacy) -- Beef, variety meats and by-products, liver, raw', '169451', 'https://fdc.nal.usda.gov/food-details/169451/nutrients', CURRENT_DATE),  -- Beef, variety meats and by-products, liver, raw
  ('כבש (טלה) צלוי', 309, 22.55, 'meat_poultry', 'roasted', 'USDA FoodData Central (SR Legacy) -- Lamb, loin, separable lean and fat, trimmed to 1/4" fat, choice, cooked, roasted', '172490', 'https://fdc.nal.usda.gov/food-details/172490/nutrients', CURRENT_DATE),  -- Lamb, loin, separable lean and fat, trimmed to 1/4" fat, choice, cooked, roasted
  ('לב בקר מבושל', 165, 28.48, 'meat_poultry', 'cooked', 'USDA FoodData Central (SR Legacy) -- Beef, variety meats and by-products, heart, cooked, simmered', '169448', 'https://fdc.nal.usda.gov/food-details/169448/nutrients', CURRENT_DATE),  -- Beef, variety meats and by-products, heart, cooked, simmered
  ('לשון בקר מבושלת', 284, 19.29, 'meat_poultry', 'cooked', 'USDA FoodData Central (SR Legacy) -- Beef, variety meats and by-products, tongue, cooked, simmered', '170598', 'https://fdc.nal.usda.gov/food-details/170598/nutrients', CURRENT_DATE),  -- Beef, variety meats and by-products, tongue, cooked, simmered
  ('כרעיים טלה צלויות', 225, 26.41, 'meat_poultry', 'roasted', 'USDA FoodData Central (SR Legacy) -- Lamb, leg, shank half, separable lean and fat, trimmed to 1/4" fat, choice, cooked, roasted', '172485', 'https://fdc.nal.usda.gov/food-details/172485/nutrients', CURRENT_DATE),  -- Lamb, leg, shank half, separable lean and fat, trimmed to 1/4" fat, choice, cooked, roasted
  ('כבש טחון גולמי', 282, 16.56, 'meat_poultry', 'raw', 'USDA FoodData Central (SR Legacy) -- Lamb, ground, raw', '174370', 'https://fdc.nal.usda.gov/food-details/174370/nutrients', CURRENT_DATE),  -- Lamb, ground, raw
  ('עגל (בשר עגל) צלוי', 175, 26.32, 'meat_poultry', 'roasted', 'USDA FoodData Central (SR Legacy) -- Veal, loin, separable lean only, cooked, roasted', '175274', 'https://fdc.nal.usda.gov/food-details/175274/nutrients', CURRENT_DATE),  -- Veal, loin, separable lean only, cooked, roasted
  ('הודו שלם צלוי (חזה)', 147, 30.13, 'meat_poultry', 'roasted', 'USDA FoodData Central (SR Legacy) -- Turkey, whole, breast, meat only, cooked, roasted', '171496', 'https://fdc.nal.usda.gov/food-details/171496/nutrients', CURRENT_DATE),  -- Turkey, whole, breast, meat only, cooked, roasted
  ('הודו טחון גולמי', 148, 19.66, 'meat_poultry', 'raw', 'USDA FoodData Central (SR Legacy) -- Turkey, Ground, raw', '171505', 'https://fdc.nal.usda.gov/food-details/171505/nutrients', CURRENT_DATE),  -- Turkey, Ground, raw
  ('אווז צלוי', 305, 25.16, 'meat_poultry', 'roasted', 'USDA FoodData Central (SR Legacy) -- Goose, domesticated, meat and skin, cooked, roasted', '172412', 'https://fdc.nal.usda.gov/food-details/172412/nutrients', CURRENT_DATE),  -- Goose, domesticated, meat and skin, cooked, roasted
  ('ברווז צלוי (עם עור)', 336, 18.9, 'meat_poultry', 'roasted', 'USDA FoodData Central (Survey (FNDDS)) -- Duck, roasted, skin eaten', '2706139', 'https://fdc.nal.usda.gov/food-details/2706139/nutrients', CURRENT_DATE),  -- Duck, roasted, skin eaten
  ('נקניק סלמי', 261, 12.6, 'meat_poultry', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Salami, cooked, beef', '172935', 'https://fdc.nal.usda.gov/food-details/172935/nutrients', CURRENT_DATE),  -- Salami, cooked, beef
  ('כבד עוף גולמי', 119, 16.92, 'meat_poultry', 'raw', 'USDA FoodData Central (SR Legacy) -- Chicken, liver, all classes, raw', '171060', 'https://fdc.nal.usda.gov/food-details/171060/nutrients', CURRENT_DATE),  -- Chicken, liver, all classes, raw
  ('סלמון גולמי', 188, 20.4, 'fish_seafood', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Fish, salmon, raw', '2706284', 'https://fdc.nal.usda.gov/food-details/2706284/nutrients', CURRENT_DATE),  -- Fish, salmon, raw
  ('טונה טרייה גולמית', 109, 24.4, 'fish_seafood', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Fish, tuna, raw', '2706308', 'https://fdc.nal.usda.gov/food-details/2706308/nutrients', CURRENT_DATE),  -- Fish, tuna, raw
  ('דג אמנון גולמי', 96, 20.08, 'fish_seafood', 'raw', 'USDA FoodData Central (SR Legacy) -- Fish, tilapia, raw', '175176', 'https://fdc.nal.usda.gov/food-details/175176/nutrients', CURRENT_DATE),  -- Fish, tilapia, raw
  ('קורקבן עוף מבושל', 154, 30.39, 'meat_poultry', 'cooked', 'USDA FoodData Central (SR Legacy) -- Chicken, gizzard, all classes, cooked, simmered', '171457', 'https://fdc.nal.usda.gov/food-details/171457/nutrients', CURRENT_DATE),  -- Chicken, gizzard, all classes, cooked, simmered
  ('מקרל (קוליוס) מבושל', 262, 23.85, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Fish, mackerel, Atlantic, cooked, dry heat', '175120', 'https://fdc.nal.usda.gov/food-details/175120/nutrients', CURRENT_DATE),  -- Fish, mackerel, Atlantic, cooked, dry heat
  ('הליבוט (פוטית) מבושל', 239, 18.42, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Fish, halibut, greenland, cooked, dry heat', '174232', 'https://fdc.nal.usda.gov/food-details/174232/nutrients', CURRENT_DATE),  -- Fish, halibut, greenland, cooked, dry heat
  ('בס ים (לברק) גולמי', 97, 18.43, 'fish_seafood', 'raw', 'USDA FoodData Central (SR Legacy) -- Fish, sea bass, mixed species, raw', '175142', 'https://fdc.nal.usda.gov/food-details/175142/nutrients', CURRENT_DATE),  -- Fish, sea bass, mixed species, raw
  ('דג בקלה גולמי', 65.9855, 16.06875, 'fish_seafood', 'raw', 'USDA FoodData Central (Foundation) -- Fish, cod, Atlantic, wild caught, raw', '2684444', 'https://fdc.nal.usda.gov/food-details/2684444/nutrients', CURRENT_DATE),  -- Fish, cod, Atlantic, wild caught, raw
  ('תמנון מבושל', 164, 29.82, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Mollusks, octopus, common, cooked, moist heat', '174249', 'https://fdc.nal.usda.gov/food-details/174249/nutrients', CURRENT_DATE),  -- Mollusks, octopus, common, cooked, moist heat
  ('קלמארי (דיונון) מטוגן', 234, 13.8, 'fish_seafood', 'fried', 'USDA FoodData Central (Survey (FNDDS)) -- Calamari, fried', '2706334', 'https://fdc.nal.usda.gov/food-details/2706334/nutrients', CURRENT_DATE),  -- Calamari, fried
  ('פורל גולמי', 119, 20.48, 'fish_seafood', 'raw', 'USDA FoodData Central (SR Legacy) -- Fish, trout, rainbow, wild, raw', '175154', 'https://fdc.nal.usda.gov/food-details/175154/nutrients', CURRENT_DATE),  -- Fish, trout, rainbow, wild, raw
  ('סרטן (תפוסי ים) מבושל', 83, 17.88, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Crustaceans, crab, blue, cooked, moist heat', '174205', 'https://fdc.nal.usda.gov/food-details/174205/nutrients', CURRENT_DATE),  -- Crustaceans, crab, blue, cooked, moist heat
  ('שרימפס גולמי', 85, 20.1, 'fish_seafood', 'raw', 'USDA FoodData Central (SR Legacy) -- Crustaceans, shrimp, raw', '175179', 'https://fdc.nal.usda.gov/food-details/175179/nutrients', CURRENT_DATE),  -- Crustaceans, shrimp, raw
  ('לובסטר מבושל', 89, 19, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Crustaceans, lobster, northern, cooked, moist heat', '174209', 'https://fdc.nal.usda.gov/food-details/174209/nutrients', CURRENT_DATE),  -- Crustaceans, lobster, northern, cooked, moist heat
  ('סקאלופס (צדפות מסתובבות) מבושלות', 111, 20.54, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Mollusks, scallop, (bay and sea), cooked, steamed', '167742', 'https://fdc.nal.usda.gov/food-details/167742/nutrients', CURRENT_DATE),  -- Mollusks, scallop, (bay and sea), cooked, steamed
  ('קציצות דגים (גפילטע פיש)', 82, 10.4, 'fish_seafood', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Gefilte fish', '2706551', 'https://fdc.nal.usda.gov/food-details/2706551/nutrients', CURRENT_DATE),  -- Gefilte fish
  ('יוגורט יווני 0%', 93, 7.64, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Yogurt, Greek, 2% fat, mango, CHOBANI', '172199', 'https://fdc.nal.usda.gov/food-details/172199/nutrients', CURRENT_DATE),  -- Yogurt, Greek, 2% fat, mango, CHOBANI
  ('יוגורט אפרסק', 80, 7.76, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Yogurt, Greek, nonfat, peach, CHOBANI', '171311', 'https://fdc.nal.usda.gov/food-details/171311/nutrients', CURRENT_DATE),  -- Yogurt, Greek, nonfat, peach, CHOBANI
  ('קפיר', 52, 3.59, 'dairy', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Kefir', '2705394', 'https://fdc.nal.usda.gov/food-details/2705394/nutrients', CURRENT_DATE),  -- Kefir
  ('גבינת שמנת לייט', 264, 9.09, 'dairy', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Cream cheese, light', '2705762', 'https://fdc.nal.usda.gov/food-details/2705762/nutrients', CURRENT_DATE),  -- Cream cheese, light
  ('בלו צ''יז (רוקפור)', 353, 21.4, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cheese, blue', '172175', 'https://fdc.nal.usda.gov/food-details/172175/nutrients', CURRENT_DATE),  -- Cheese, blue
  ('קממבר', 300, 19.8, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cheese, camembert', '172178', 'https://fdc.nal.usda.gov/food-details/172178/nutrients', CURRENT_DATE),  -- Cheese, camembert
  ('גאודה', 356, 24.94, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cheese, gouda', '171241', 'https://fdc.nal.usda.gov/food-details/171241/nutrients', CURRENT_DATE),  -- Cheese, gouda
  ('גבינת עז רכה', 264, 18.52, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cheese, goat, soft type', '173435', 'https://fdc.nal.usda.gov/food-details/173435/nutrients', CURRENT_DATE),  -- Cheese, goat, soft type
  ('צ''דר', 408, 23.3, 'dairy', 'as_sold', 'USDA FoodData Central (Foundation) -- Cheese, cheddar', '328637', 'https://fdc.nal.usda.gov/food-details/328637/nutrients', CURRENT_DATE),  -- Cheese, cheddar
  ('גלידת שוקולד', 216, 3.8, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Ice creams, chocolate', '168809', 'https://fdc.nal.usda.gov/food-details/168809/nutrients', CURRENT_DATE),  -- Ice creams, chocolate
  ('פרוזן יוגורט', 131, 3, 'dairy', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Frozen yogurts, chocolate', '168104', 'https://fdc.nal.usda.gov/food-details/168104/nutrients', CURRENT_DATE),  -- Frozen yogurts, chocolate
  ('אגוזי מקדמיה', 716, 7.79, 'nuts_seeds_fats', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Macadamia nuts', '2707503', 'https://fdc.nal.usda.gov/food-details/2707503/nutrients', CURRENT_DATE),  -- Macadamia nuts
  ('שקדים קלויים ומלוחים', 607, 21.23, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Nuts, almonds, oil roasted, lightly salted', '168602', 'https://fdc.nal.usda.gov/food-details/168602/nutrients', CURRENT_DATE),  -- Nuts, almonds, oil roasted, lightly salted
  ('אגוזי ברזיל', 659, 14.3, 'nuts_seeds_fats', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Brazil nuts', '2707492', 'https://fdc.nal.usda.gov/food-details/2707492/nutrients', CURRENT_DATE),  -- Brazil nuts
  ('זרעי צ''יה', 486, 16.5, 'nuts_seeds_fats', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Chia seeds', '2707590', 'https://fdc.nal.usda.gov/food-details/2707590/nutrients', CURRENT_DATE),  -- Chia seeds
  ('בוטנים קלויים ומלוחים', 599, 28, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Peanuts, roasted, salted', '2707515', 'https://fdc.nal.usda.gov/food-details/2707515/nutrients', CURRENT_DATE),  -- Peanuts, roasted, salted
  ('זרעי שומשום', 631, 20.4, 'nuts_seeds_fats', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Sesame seeds', '2707586', 'https://fdc.nal.usda.gov/food-details/2707586/nutrients', CURRENT_DATE),  -- Sesame seeds
  ('זרעי פשתן', 545, 18, 'nuts_seeds_fats', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Flax seeds', '2707588', 'https://fdc.nal.usda.gov/food-details/2707588/nutrients', CURRENT_DATE),  -- Flax seeds
  ('אגוזי פקאן', 750, 9.96, 'nuts_seeds_fats', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Pecans, NFS', '2707521', 'https://fdc.nal.usda.gov/food-details/2707521/nutrients', CURRENT_DATE),  -- Pecans, NFS
  ('חמאת קשיו', 609, 12.1, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Cashew butter', '2707536', 'https://fdc.nal.usda.gov/food-details/2707536/nutrients', CURRENT_DATE),  -- Cashew butter
  ('שמן קנולה', 900, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Canola oil', '2710188', 'https://fdc.nal.usda.gov/food-details/2710188/nutrients', CURRENT_DATE),  -- Canola oil
  ('שמן קוקוס', 892, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Oil, coconut', '171412', 'https://fdc.nal.usda.gov/food-details/171412/nutrients', CURRENT_DATE),  -- Oil, coconut
  ('שמן שומשום', 884, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Sesame oil', '2710190', 'https://fdc.nal.usda.gov/food-details/2710190/nutrients', CURRENT_DATE),  -- Sesame oil
  ('שמן אבוקדו', 884, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Oil, avocado', '173573', 'https://fdc.nal.usda.gov/food-details/173573/nutrients', CURRENT_DATE),  -- Oil, avocado
  ('שמן סויה', 900, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Soybean oil', '2710191', 'https://fdc.nal.usda.gov/food-details/2710191/nutrients', CURRENT_DATE),  -- Soybean oil
  ('שוקולד מריר 70%', 598, 7.79, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Chocolate, dark, 70-85% cacao solids', '170273', 'https://fdc.nal.usda.gov/food-details/170273/nutrients', CURRENT_DATE),  -- Chocolate, dark, 70-85% cacao solids
  ('קקאו אבקה (ללא סוכר)', 228, 19.6, 'sweets_snacks', 'dried', 'USDA FoodData Central (SR Legacy) -- Cocoa, dry powder, unsweetened', '169593', 'https://fdc.nal.usda.gov/food-details/169593/nutrients', CURRENT_DATE),  -- Cocoa, dry powder, unsweetened
  ('מסטיק', 360, 0, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Chewing gum', '168771', 'https://fdc.nal.usda.gov/food-details/168771/nutrients', CURRENT_DATE),  -- Chewing gum
  ('חטיף שוקולד עם בוטנים (סגנון סניקרס)', 495, 8.93, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Candies, REESE''s Fast Break, milk chocolate, peanut butter, soft nougats, candy bar', '170669', 'https://fdc.nal.usda.gov/food-details/170669/nutrients', CURRENT_DATE),  -- Candies, REESE's Fast Break, milk chocolate, peanut butter, soft nougats, candy bar
  ('קליות תירס (צ''יטוס-סגנון)', 371, 7.74, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Cereal, corn puffs', '2708454', 'https://fdc.nal.usda.gov/food-details/2708454/nutrients', CURRENT_DATE),  -- Cereal, corn puffs
  ('דוריטוס (צ''יפס תירס)', 503, 7.79, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Snacks, tortilla chips, unsalted, white corn', '168116', 'https://fdc.nal.usda.gov/food-details/168116/nutrients', CURRENT_DATE),  -- Snacks, tortilla chips, unsalted, white corn
  ('ופלה בטעם וניל', 455, 4.9, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cookies, vanilla wafers, higher fat', '174974', 'https://fdc.nal.usda.gov/food-details/174974/nutrients', CURRENT_DATE),  -- Cookies, vanilla wafers, higher fat
  ('פודינג וניל', 130, 1.45, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Puddings, vanilla, ready-to-eat', '169608', 'https://fdc.nal.usda.gov/food-details/169608/nutrients', CURRENT_DATE),  -- Puddings, vanilla, ready-to-eat
  ('מוס שוקולד', 225, 4.14, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Desserts, mousse, chocolate, prepared-from-recipe', '168777', 'https://fdc.nal.usda.gov/food-details/168777/nutrients', CURRENT_DATE),  -- Desserts, mousse, chocolate, prepared-from-recipe
  ('טפי (ריבועי סוכריות)', 541, 3.13, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Candies, HERSHEY''S SKOR Toffee Bar', '168757', 'https://fdc.nal.usda.gov/food-details/168757/nutrients', CURRENT_DATE),  -- Candies, HERSHEY'S SKOR Toffee Bar
  ('נוגט', 398, 3.33, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Candies, nougat, with almonds', '169060', 'https://fdc.nal.usda.gov/food-details/169060/nutrients', CURRENT_DATE),  -- Candies, nougat, with almonds
  ('פופקורן ממותק (קרמל)', 428, 3.77, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Popcorn, caramel coated', '2708239', 'https://fdc.nal.usda.gov/food-details/2708239/nutrients', CURRENT_DATE),  -- Popcorn, caramel coated
  ('פופקורן חמאה (מיקרוגל)', 518, 9.13, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Popcorn, microwave, butter flavored', '2708227', 'https://fdc.nal.usda.gov/food-details/2708227/nutrients', CURRENT_DATE),  -- Popcorn, microwave, butter flavored
  ('פרטצל (בייגלה קלוע)', 338, 8.2, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Pretzels, soft', '169064', 'https://fdc.nal.usda.gov/food-details/169064/nutrients', CURRENT_DATE),  -- Pretzels, soft
  ('רוטב פסטו', 580, 8.61, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Pesto sauce', '2710175', 'https://fdc.nal.usda.gov/food-details/2710175/nutrients', CURRENT_DATE),  -- Pesto sauce
  ('רוטב אלפרדו', 150, 2.12, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Alfredo sauce', '2705809', 'https://fdc.nal.usda.gov/food-details/2705809/nutrients', CURRENT_DATE),  -- Alfredo sauce
  ('רוטב טריאקי', 89, 5.93, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Teriyaki sauce', '2707445', 'https://fdc.nal.usda.gov/food-details/2707445/nutrients', CURRENT_DATE),  -- Teriyaki sauce
  ('קרמל (סוכריות)', 382, 4.6, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Candies, caramels', '167974', 'https://fdc.nal.usda.gov/food-details/167974/nutrients', CURRENT_DATE),  -- Candies, caramels
  ('רוטב וורצ''סטר', 77, 0, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Sauce, worcestershire', '171610', 'https://fdc.nal.usda.gov/food-details/171610/nutrients', CURRENT_DATE),  -- Sauce, worcestershire
  ('רוטב סלט קיסר', 542, 2.17, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Salad dressing, caesar dressing, regular', '169055', 'https://fdc.nal.usda.gov/food-details/169055/nutrients', CURRENT_DATE),  -- Salad dressing, caesar dressing, regular
  ('רנץ'' (רוטב לסלט)', 430, 1.32, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Ranch dressing', '2710212', 'https://fdc.nal.usda.gov/food-details/2710212/nutrients', CURRENT_DATE),  -- Ranch dressing
  ('חומץ בלסמי', 88, 0.49, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Vinegar, balsamic', '172241', 'https://fdc.nal.usda.gov/food-details/172241/nutrients', CURRENT_DATE),  -- Vinegar, balsamic
  ('רוטב סויה דל נתרן', 57, 9.05, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Soy sauce made from soy and wheat (shoyu), low sodium', '172473', 'https://fdc.nal.usda.gov/food-details/172473/nutrients', CURRENT_DATE),  -- Soy sauce made from soy and wheat (shoyu), low sodium
  ('ריבת משמשים', 242, 0.7, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Jams and preserves, apricot', '170645', 'https://fdc.nal.usda.gov/food-details/170645/nutrients', CURRENT_DATE),  -- Jams and preserves, apricot
  ('רוטב שוקולד נוזלי', 269, 0, 'sauce_condiment', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Chocolate syrup', '2710276', 'https://fdc.nal.usda.gov/food-details/2710276/nutrients', CURRENT_DATE),  -- Chocolate syrup
  ('מלח', 0, 0, 'spice_herb', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Salt, table', '173468', 'https://fdc.nal.usda.gov/food-details/173468/nutrients', CURRENT_DATE),  -- Salt, table
  ('כורכום טחון', 312, 9.68, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, turmeric, ground', '172231', 'https://fdc.nal.usda.gov/food-details/172231/nutrients', CURRENT_DATE),  -- Spices, turmeric, ground
  ('שמן חמניות', 900, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Sunflower oil', '2710192', 'https://fdc.nal.usda.gov/food-details/2710192/nutrients', CURRENT_DATE),  -- Sunflower oil
  ('קינמון טחון', 247, 3.99, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, cinnamon, ground', '171320', 'https://fdc.nal.usda.gov/food-details/171320/nutrients', CURRENT_DATE),  -- Spices, cinnamon, ground
  ('שום אבקה', 331, 16.55, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, garlic powder', '171325', 'https://fdc.nal.usda.gov/food-details/171325/nutrients', CURRENT_DATE),  -- Spices, garlic powder
  ('אורגנו מיובש', 265, 9, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, oregano, dried', '171328', 'https://fdc.nal.usda.gov/food-details/171328/nutrients', CURRENT_DATE),  -- Spices, oregano, dried
  ('בצל אבקה', 341, 10.41, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, onion powder', '171327', 'https://fdc.nal.usda.gov/food-details/171327/nutrients', CURRENT_DATE),  -- Spices, onion powder
  ('בזיליקום מיובש', 233, 22.98, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, basil, dried', '171317', 'https://fdc.nal.usda.gov/food-details/171317/nutrients', CURRENT_DATE),  -- Spices, basil, dried
  ('פטרוזיליה טרייה', 36, 2.97, 'spice_herb', 'raw', 'USDA FoodData Central (SR Legacy) -- Parsley, fresh', '170416', 'https://fdc.nal.usda.gov/food-details/170416/nutrients', CURRENT_DATE),  -- Parsley, fresh
  ('ג''ינג''ר טרי (זנגביל)', 80, 1.82, 'spice_herb', 'raw', 'USDA FoodData Central (SR Legacy) -- Ginger root, raw', '169231', 'https://fdc.nal.usda.gov/food-details/169231/nutrients', CURRENT_DATE),  -- Ginger root, raw
  ('שמיר טרי', 43, 3.46, 'spice_herb', 'raw', 'USDA FoodData Central (SR Legacy) -- Dill weed, fresh', '172233', 'https://fdc.nal.usda.gov/food-details/172233/nutrients', CURRENT_DATE),  -- Dill weed, fresh
  ('כוסברה טרייה', 23, 2.13, 'spice_herb', 'raw', 'USDA FoodData Central (SR Legacy) -- Coriander (cilantro) leaves, raw', '169997', 'https://fdc.nal.usda.gov/food-details/169997/nutrients', CURRENT_DATE),  -- Coriander (cilantro) leaves, raw
  ('קארי אבקה (תערובת)', 325, 14.29, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Spices, curry powder', '170924', 'https://fdc.nal.usda.gov/food-details/170924/nutrients', CURRENT_DATE),  -- Spices, curry powder
  ('אבקת אפייה', 97, 0.1, 'spice_herb', 'dried', 'USDA FoodData Central (SR Legacy) -- Leavening agents, baking powder, low-sodium', '172805', 'https://fdc.nal.usda.gov/food-details/172805/nutrients', CURRENT_DATE),  -- Leavening agents, baking powder, low-sodium
  ('מיץ ענבים לבן', 66.135, 0.09375, 'beverage', 'as_sold', 'USDA FoodData Central (Foundation) -- Grape juice, white, with added vitamin C, from concentrate, shelf stable', '2003593', 'https://fdc.nal.usda.gov/food-details/2003593/nutrients', CURRENT_DATE),  -- Grape juice, white, with added vitamin C, from concentrate, shelf stable
  ('מיץ גזר', 40, 0.95, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Carrot juice, canned', '170491', 'https://fdc.nal.usda.gov/food-details/170491/nutrients', CURRENT_DATE),  -- Carrot juice, canned
  ('מיץ עגבניות', 22, 0.93, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tomato juice cocktail', '2709730', 'https://fdc.nal.usda.gov/food-details/2709730/nutrients', CURRENT_DATE),  -- Tomato juice cocktail
  ('מיץ רימונים', 54, 0.15, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Pomegranate juice, bottled', '167787', 'https://fdc.nal.usda.gov/food-details/167787/nutrients', CURRENT_DATE),  -- Pomegranate juice, bottled
  ('מיץ קרנברי', 46, 0.39, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Cranberry juice, unsweetened', '168117', 'https://fdc.nal.usda.gov/food-details/168117/nutrients', CURRENT_DATE),  -- Cranberry juice, unsweetened
  ('מיץ אננס', 51, 0.41, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Orange Pineapple Juice Blend', '167792', 'https://fdc.nal.usda.gov/food-details/167792/nutrients', CURRENT_DATE),  -- Orange Pineapple Juice Blend
  ('קפוצ''ינו', 27, 1.71, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Coffee, Cappuccino', '2710472', 'https://fdc.nal.usda.gov/food-details/2710472/nutrients', CURRENT_DATE),  -- Coffee, Cappuccino
  ('תה ירוק', 27, 0, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tea, iced, bottled, green', '2710533', 'https://fdc.nal.usda.gov/food-details/2710533/nutrients', CURRENT_DATE),  -- Tea, iced, bottled, green
  ('תה צמחים', 2, 0.12, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Tea, herbal, brewed, Hohoysi (Hopi)', '169828', 'https://fdc.nal.usda.gov/food-details/169828/nutrients', CURRENT_DATE),  -- Tea, herbal, brewed, Hohoysi (Hopi)
  ('מאלט (בירה שחורה)', 37, 0.21, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Malt beverage, includes non-alcoholic beer', '174863', 'https://fdc.nal.usda.gov/food-details/174863/nutrients', CURRENT_DATE),  -- Malt beverage, includes non-alcoholic beer
  ('בירה לייט (דלת אלכוהול)', 29, 0.24, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Beer, light', '2710617', 'https://fdc.nal.usda.gov/food-details/2710617/nutrients', CURRENT_DATE),  -- Beer, light
  ('יין לבן', 82, 0.07, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Wine, white', '2710689', 'https://fdc.nal.usda.gov/food-details/2710689/nutrients', CURRENT_DATE),  -- Wine, white
  ('וודקה', 231, 0, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Vodka', '2710704', 'https://fdc.nal.usda.gov/food-details/2710704/nutrients', CURRENT_DATE),  -- Vodka
  ('משקה אנרגיה', 43, 0.46, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Energy Drink', '2710756', 'https://fdc.nal.usda.gov/food-details/2710756/nutrients', CURRENT_DATE),  -- Energy Drink
  ('מיץ תפוזים סחוט טרי', 47, 0.81, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Orange juice, 100%,  freshly squeezed', '2709187', 'https://fdc.nal.usda.gov/food-details/2709187/nutrients', CURRENT_DATE),  -- Orange juice, 100%,  freshly squeezed
  ('קוקטייל פירות (משקה)', 162, 0.2, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Beverages, Fruit punch drink, frozen concentrate', '174152', 'https://fdc.nal.usda.gov/food-details/174152/nutrients', CURRENT_DATE),  -- Beverages, Fruit punch drink, frozen concentrate
  ('מרק פטריות', 74, 2.1, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Soup, cream of mushroom', '2710107', 'https://fdc.nal.usda.gov/food-details/2710107/nutrients', CURRENT_DATE),  -- Soup, cream of mushroom
  ('ספרייט', 41, 0.09, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Beverages, carbonated, lemon-lime soda, no caffeine', '173205', 'https://fdc.nal.usda.gov/food-details/173205/nutrients', CURRENT_DATE),  -- Beverages, carbonated, lemon-lime soda, no caffeine
  ('מרק בצל צרפתי', 108, 5.45, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Soup, French onion', '2710108', 'https://fdc.nal.usda.gov/food-details/2710108/nutrients', CURRENT_DATE),  -- Soup, French onion
  ('מרק מיסו', 24, 2.21, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Soup, miso or tofu', '2707455', 'https://fdc.nal.usda.gov/food-details/2707455/nutrients', CURRENT_DATE),  -- Soup, miso or tofu
  ('סלט חסה ועגבניות', 23, 1.19, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Lettuce, salad with assorted vegetables excluding tomatoes and carrots, no dressing', '2709823', 'https://fdc.nal.usda.gov/food-details/2709823/nutrients', CURRENT_DATE),  -- Lettuce, salad with assorted vegetables excluding tomatoes and carrots, no dressing
  ('סלט יווני', 48, 2.75, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Greek Salad, no dressing', '2709830', 'https://fdc.nal.usda.gov/food-details/2709830/nutrients', CURRENT_DATE),  -- Greek Salad, no dressing
  ('סלט טונה', 194, 10.1, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tuna salad, made with mayonnaise', '2706828', 'https://fdc.nal.usda.gov/food-details/2706828/nutrients', CURRENT_DATE),  -- Tuna salad, made with mayonnaise
  ('סלט ביצים', 157, 1.96, 'soup_salad', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Potato salad with egg', '173343', 'https://fdc.nal.usda.gov/food-details/173343/nutrients', CURRENT_DATE),  -- Potato salad with egg
  ('סלט קיסר עם עוף', 63, 8.52, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Chicken or turkey caesar garden salad, chicken and/or turkey, lettuce, tomato, cheese, no dressing', '2706818', 'https://fdc.nal.usda.gov/food-details/2706818/nutrients', CURRENT_DATE),  -- Chicken or turkey caesar garden salad, chicken and/or turkey, lettuce, tomato, cheese, no dressing
  ('סלט כרוב לבן (קולסלו)', 117, 0.94, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Coleslaw', '2709815', 'https://fdc.nal.usda.gov/food-details/2709815/nutrients', CURRENT_DATE),  -- Coleslaw
  ('סלט טבולה', 127, 1.64, 'soup_salad', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tabbouleh', '2709131', 'https://fdc.nal.usda.gov/food-details/2709131/nutrients', CURRENT_DATE),  -- Tabbouleh
  ('רול טורטייה עם טונה', 244, 10.6, 'sandwich', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tuna salad sandwich wrap', '2707038', 'https://fdc.nal.usda.gov/food-details/2707038/nutrients', CURRENT_DATE),  -- Tuna salad sandwich wrap
  ('הוט דוג (נקניקיה בלחמנייה)', 202, 10, 'sandwich', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Chili hot dog, no bun', '2706409', 'https://fdc.nal.usda.gov/food-details/2706409/nutrients', CURRENT_DATE),  -- Chili hot dog, no bun
  ('עוף בקארי', 107, 6.48, 'prepared_dish', 'cooked', 'USDA FoodData Central (Survey (FNDDS)) -- Chicken curry', '2706437', 'https://fdc.nal.usda.gov/food-details/2706437/nutrients', CURRENT_DATE),  -- Chicken curry
  ('תבשיל ירקות מוקפצים (סטיר פריי)', 71, 2.01, 'prepared_dish', 'fried', 'USDA FoodData Central (Survey (FNDDS)) -- Asian stir fry vegetables, cooked, fat added', '2710036', 'https://fdc.nal.usda.gov/food-details/2710036/nutrients', CURRENT_DATE),  -- Asian stir fry vegetables, cooked, fat added
  ('אורז מוקפץ עם עוף (סיני)', 173, 7.28, 'prepared_dish', 'fried', 'USDA FoodData Central (Survey (FNDDS)) -- Rice, fried, with chicken', '2708953', 'https://fdc.nal.usda.gov/food-details/2708953/nutrients', CURRENT_DATE),  -- Rice, fried, with chicken
  ('פאד תאי', 154, 8.13, 'prepared_dish', 'cooked', 'USDA FoodData Central (Survey (FNDDS)) -- Pad Thai, NFS', '2708804', 'https://fdc.nal.usda.gov/food-details/2708804/nutrients', CURRENT_DATE),  -- Pad Thai, NFS
  ('קסדייה גבינה', 316, 13.4, 'prepared_dish', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Quesadilla, cheese only', '2708591', 'https://fdc.nal.usda.gov/food-details/2708591/nutrients', CURRENT_DATE),  -- Quesadilla, cheese only
  ('טאקו בשר', 257, 16.7, 'prepared_dish', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Taco, flour tortilla, beef, cheese', '2708522', 'https://fdc.nal.usda.gov/food-details/2708522/nutrients', CURRENT_DATE),  -- Taco, flour tortilla, beef, cheese
  ('צ''ילי קון קרנה', 107, 5.8, 'prepared_dish', 'cooked', 'USDA FoodData Central (SR Legacy) -- Chili con carne with beans, canned entree', '172097', 'https://fdc.nal.usda.gov/food-details/172097/nutrients', CURRENT_DATE),  -- Chili con carne with beans, canned entree
  ('קלצונה גבינה', 343, 14.8, 'prepared_dish', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Calzone, with meat and cheese', '2708685', 'https://fdc.nal.usda.gov/food-details/2708685/nutrients', CURRENT_DATE),  -- Calzone, with meat and cheese
  ('פרנץ'' טוסט', 278, 7.52, 'prepared_dish', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- French toast sticks', '2708338', 'https://fdc.nal.usda.gov/food-details/2708338/nutrients', CURRENT_DATE),  -- French toast sticks
  ('כבד קצוץ (אשכנזי)', 226, 12.9, 'prepared_dish', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Livers, chicken, chopped, with eggs and onion', '2706875', 'https://fdc.nal.usda.gov/food-details/2706875/nutrients', CURRENT_DATE),  -- Livers, chicken, chopped, with eggs and onion
  ('תות עץ (מורוס)', 43, 1.44, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Mulberries, raw', '169913', 'https://fdc.nal.usda.gov/food-details/169913/nutrients', CURRENT_DATE),  -- Mulberries, raw
  ('תמר מדג''ול', 277, 1.81, 'fruit', 'raw', 'USDA FoodData Central (SR Legacy) -- Dates, medjool', '168191', 'https://fdc.nal.usda.gov/food-details/168191/nutrients', CURRENT_DATE),  -- Dates, medjool
  ('חסה חמאה (ליטוס)', 13, 1.35, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Lettuce, butterhead (includes boston and bibb types), raw', '168429', 'https://fdc.nal.usda.gov/food-details/168429/nutrients', CURRENT_DATE),  -- Lettuce, butterhead (includes boston and bibb types), raw
  ('עגבניות מיובשות ולא כבושות', 258, 14.11, 'vegetable', 'dried', 'USDA FoodData Central (SR Legacy) -- Tomatoes, sun-dried', '168567', 'https://fdc.nal.usda.gov/food-details/168567/nutrients', CURRENT_DATE),  -- Tomatoes, sun-dried
  ('בוק צ''וי', 20.259, 1.02375, 'vegetable', 'raw', 'USDA FoodData Central (Foundation) -- Cabbage, bok choy, raw', '2685572', 'https://fdc.nal.usda.gov/food-details/2685572/nutrients', CURRENT_DATE),  -- Cabbage, bok choy, raw
  ('קולורבי מבושל', 29, 1.8, 'vegetable', 'boiled', 'USDA FoodData Central (SR Legacy) -- Kohlrabi, cooked, boiled, drained, with salt', '169357', 'https://fdc.nal.usda.gov/food-details/169357/nutrients', CURRENT_DATE),  -- Kohlrabi, cooked, boiled, drained, with salt
  ('טף (דגן אתיופי) מבושל', 101, 3.87, 'grain_carb', 'cooked', 'USDA FoodData Central (SR Legacy) -- Teff, cooked', '168918', 'https://fdc.nal.usda.gov/food-details/168918/nutrients', CURRENT_DATE),  -- Teff, cooked
  ('אמרנט מבושל', 102, 3.8, 'grain_carb', 'cooked', 'USDA FoodData Central (SR Legacy) -- Amaranth grain, cooked', '170683', 'https://fdc.nal.usda.gov/food-details/170683/nutrients', CURRENT_DATE),  -- Amaranth grain, cooked
  ('לחמניית סובה (חיטה מלאה קטנה)', 273, 8.6, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Roll, whole wheat', '2707749', 'https://fdc.nal.usda.gov/food-details/2707749/nutrients', CURRENT_DATE),  -- Roll, whole wheat
  ('קרקר חיטה מלאה', 427, 10.58, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Crackers, whole-wheat', '172749', 'https://fdc.nal.usda.gov/food-details/172749/nutrients', CURRENT_DATE),  -- Crackers, whole-wheat
  ('פריכית תירס', 385, 8.4, 'bread_bakery', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Snacks, rice cakes, brown rice, corn', '169679', 'https://fdc.nal.usda.gov/food-details/169679/nutrients', CURRENT_DATE),  -- Snacks, rice cakes, brown rice, corn
  ('לחמנייה חיטה לבנה קטנה', 279, 9.77, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Roll, white, soft', '2707654', 'https://fdc.nal.usda.gov/food-details/2707654/nutrients', CURRENT_DATE),  -- Roll, white, soft
  ('נתח כתף כבש גולמי', 154, 19.72, 'meat_poultry', 'raw', 'USDA FoodData Central (SR Legacy) -- Lamb, New Zealand, imported, square-cut shoulder, separable lean only, raw', '175264', 'https://fdc.nal.usda.gov/food-details/175264/nutrients', CURRENT_DATE),  -- Lamb, New Zealand, imported, square-cut shoulder, separable lean only, raw
  ('שקדי מרק (קרוטונים)', 465, 10.8, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Croutons', '2707697', 'https://fdc.nal.usda.gov/food-details/2707697/nutrients', CURRENT_DATE),  -- Croutons
  ('פסטרמה בקר', 147, 21.8, 'meat_poultry', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Beef, cured, pastrami', '170204', 'https://fdc.nal.usda.gov/food-details/170204/nutrients', CURRENT_DATE),  -- Beef, cured, pastrami
  ('סול (לימונית) מבושל', 86, 15.24, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Fish, flatfish (flounder and sole species), cooked, dry heat', '174197', 'https://fdc.nal.usda.gov/food-details/174197/nutrients', CURRENT_DATE),  -- Fish, flatfish (flounder and sole species), cooked, dry heat
  ('קונכיות (בלאדי) מבושלות', 148, 25.55, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Mollusks, clam, mixed species, cooked, moist heat', '171975', 'https://fdc.nal.usda.gov/food-details/171975/nutrients', CURRENT_DATE),  -- Mollusks, clam, mixed species, cooked, moist heat
  ('קרפיון מבושל', 162, 22.86, 'fish_seafood', 'cooked', 'USDA FoodData Central (SR Legacy) -- Fish, carp, cooked, dry heat', '174185', 'https://fdc.nal.usda.gov/food-details/174185/nutrients', CURRENT_DATE),  -- Fish, carp, cooked, dry heat
  ('נקניק עוף מעושן', 216, 13.6, 'meat_poultry', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Sausage, chicken, beef, pork, skinless, smoked', '174605', 'https://fdc.nal.usda.gov/food-details/174605/nutrients', CURRENT_DATE),  -- Sausage, chicken, beef, pork, skinless, smoked
  ('שמנת לקפה (נוזלית)', 136, 1, 'dairy', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Coffee creamer, liquid', '2705600', 'https://fdc.nal.usda.gov/food-details/2705600/nutrients', CURRENT_DATE),  -- Coffee creamer, liquid
  ('יוגורט סויה', 90, 4.83, 'dairy', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Yogurt, soy', '2707444', 'https://fdc.nal.usda.gov/food-details/2707444/nutrients', CURRENT_DATE),  -- Yogurt, soy
  ('אגוזי פקאן קלויים', 681, 6.71, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Pecans, honey roasted', '2707525', 'https://fdc.nal.usda.gov/food-details/2707525/nutrients', CURRENT_DATE),  -- Pecans, honey roasted
  ('שמן פשתן', 884, 0.11, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Flaxseed oil', '2710185', 'https://fdc.nal.usda.gov/food-details/2710185/nutrients', CURRENT_DATE),  -- Flaxseed oil
  ('עוגיות ג''ינג''ר', 424, 4.67, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Archway Home Style Cookies, Reduced Fat Ginger Snaps', '175077', 'https://fdc.nal.usda.gov/food-details/175077/nutrients', CURRENT_DATE),  -- Archway Home Style Cookies, Reduced Fat Ginger Snaps
  ('שקדים בציפוי שוקולד', 560, 13, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Almonds, chocolate covered candy', '2710326', 'https://fdc.nal.usda.gov/food-details/2710326/nutrients', CURRENT_DATE),  -- Almonds, chocolate covered candy
  ('צימוקים בציפוי שוקולד', 422, 4.4, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Candies, NESTLE, RAISINETS Chocolate Covered Raisins', '169587', 'https://fdc.nal.usda.gov/food-details/169587/nutrients', CURRENT_DATE),  -- Candies, NESTLE, RAISINETS Chocolate Covered Raisins
  ('שוקו קר (משקה מוכן)', 50, 0.63, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Beverages, almond milk, chocolate, ready-to-drink', '174820', 'https://fdc.nal.usda.gov/food-details/174820/nutrients', CURRENT_DATE),  -- Beverages, almond milk, chocolate, ready-to-drink
  ('סירופ מייפל', 260, 0.04, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Syrups, maple', '169661', 'https://fdc.nal.usda.gov/food-details/169661/nutrients', CURRENT_DATE),  -- Syrups, maple
  ('סירופ אגבה', 310, 0.09, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Sweetener, syrup, agave', '170277', 'https://fdc.nal.usda.gov/food-details/170277/nutrients', CURRENT_DATE),  -- Sweetener, syrup, agave
  ('שמן חריע (ספלור)', 900, 0, 'nuts_seeds_fats', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Safflower oil', '2710189', 'https://fdc.nal.usda.gov/food-details/2710189/nutrients', CURRENT_DATE),  -- Safflower oil
  ('תבשיל בקר ותפוחי אדמה', 220, 14.6, 'prepared_dish', 'cooked', 'USDA FoodData Central (Survey (FNDDS)) -- Beef stew with potatoes, Puerto Rican style', '2706503', 'https://fdc.nal.usda.gov/food-details/2706503/nutrients', CURRENT_DATE),  -- Beef stew with potatoes, Puerto Rican style
  ('משמש בשימורים בסירופ כבד', 83, 0.64, 'fruit', 'canned_drained', 'USDA FoodData Central (SR Legacy) -- Apricots, canned, heavy syrup, drained', '167768', 'https://fdc.nal.usda.gov/food-details/167768/nutrients', CURRENT_DATE),  -- Apricots, canned, heavy syrup, drained
  ('כרוב סגול מבושל', 29, 1.51, 'vegetable', 'boiled', 'USDA FoodData Central (SR Legacy) -- Cabbage, red, cooked, boiled, drained, with salt', '168515', 'https://fdc.nal.usda.gov/food-details/168515/nutrients', CURRENT_DATE),  -- Cabbage, red, cooked, boiled, drained, with salt
  ('חסה סלנובה (מעורבת)', 21, 1.31, 'vegetable', 'raw', 'USDA FoodData Central (Survey (FNDDS)) -- Mixed salad greens, raw', '2709792', 'https://fdc.nal.usda.gov/food-details/2709792/nutrients', CURRENT_DATE),  -- Mixed salad greens, raw
  ('כרוב סגול', 31, 1.43, 'vegetable', 'raw', 'USDA FoodData Central (SR Legacy) -- Cabbage, red, raw', '169977', 'https://fdc.nal.usda.gov/food-details/169977/nutrients', CURRENT_DATE),  -- Cabbage, red, raw
  ('קמח כוסמין מלא', 363.679, 14.475, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Flour, spelt, whole grain', '2003587', 'https://fdc.nal.usda.gov/food-details/2003587/nutrients', CURRENT_DATE),  -- Flour, spelt, whole grain
  ('קמח כוסמת', 357.968, 8.88492, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Flour, buckwheat', '2512374', 'https://fdc.nal.usda.gov/food-details/2512374/nutrients', CURRENT_DATE),  -- Flour, buckwheat
  ('לחם טורטיה מלאה', 310, 9.76, 'bread_bakery', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tortilla, whole wheat', '2707825', 'https://fdc.nal.usda.gov/food-details/2707825/nutrients', CURRENT_DATE),  -- Tortilla, whole wheat
  ('סטייק כתף (צ''אק איי) גולמי', 227, 18.86, 'meat_poultry', 'raw', 'USDA FoodData Central (SR Legacy) -- Beef, chuck eye steak, boneless, separable lean and fat, trimmed to 0" fat, choice, raw', '170834', 'https://fdc.nal.usda.gov/food-details/170834/nutrients', CURRENT_DATE),  -- Beef, chuck eye steak, boneless, separable lean and fat, trimmed to 0" fat, choice, raw
  ('פודינג אורז', 108, 3.23, 'sweets_snacks', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Pudding, rice', '2705685', 'https://fdc.nal.usda.gov/food-details/2705685/nutrients', CURRENT_DATE),  -- Pudding, rice
  ('קומבוצ''ה', 16, 0.1, 'beverage', 'as_sold', 'USDA FoodData Central (Survey (FNDDS)) -- Tea, kombucha', '2710509', 'https://fdc.nal.usda.gov/food-details/2710509/nutrients', CURRENT_DATE),  -- Tea, kombucha
  ('מיץ אשכוליות', 39, 0.5, 'beverage', 'as_sold', 'USDA FoodData Central (SR Legacy) -- Grapefruit juice, pink, raw', '167774', 'https://fdc.nal.usda.gov/food-details/167774/nutrients', CURRENT_DATE),  -- Grapefruit juice, pink, raw
  ('אורז שחור גולמי', 369.97, 7.56875, 'grain_carb', 'raw', 'USDA FoodData Central (Foundation) -- Rice, black, unenriched, raw', '2710825', 'https://fdc.nal.usda.gov/food-details/2710825/nutrients', CURRENT_DATE),  -- Rice, black, unenriched, raw
  ('קציצות סלמון', 285, 16.1, 'prepared_dish', 'fried', 'USDA FoodData Central (Survey (FNDDS)) -- Fish, salmon cake or patty', '2706552', 'https://fdc.nal.usda.gov/food-details/2706552/nutrients', CURRENT_DATE)  -- Fish, salmon cake or patty
on conflict ((lower(name))) do nothing;
